### ISSUE TITLE
Old version in chef supermarket

### ISSUE THREAD

**Issue by spuder** [atomic-penguin/cookbook-snmp#33]
The chef supermaket has version 0.4, whereas github has 3.x.x

Are there plans to push the latest version to the supermarket soon? The readme appears all garbled on the supermarket page. 

https://supermarket.chef.io/cookbooks/snmp/versions/0.0.4#berkshelf

**Comment by atomic-penguin** [comment]
Supermarket has 3.0.1, which is the same as the most recent tag here.  There is a drop-down box to select different versions on the supermarket.

Alternatively, you could just change the 0.0.4 to 3.0.1 in your URL bar.  I don't know where the anchor #berkshelf came from, but you can drop that.

**Comment by spuder** [comment]
Thanks, looking closer it seems that version 4 is for some reason the top hit in google.
